# Generated by Django 3.0.6 on 2023-10-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationrecord',
            name='operation_content',
            field=models.CharField(max_length=256, verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='notes',
            field=models.CharField(default='无', max_length=1024, verbose_name='备注'),
        ),
    ]
