# Generated by Django 3.0.6 on 2023-10-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20231013_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='monthly_modifications',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='remaining_modifications',
        ),
    ]
